# Generated by Django 4.1.2 on 2022-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_of_booked_seats',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateField(),
        ),
    ]
