# Generated by Django 4.1.2 on 2022-11-15 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0005_following_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="following",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="following",
            name="following",
        ),
        migrations.AddField(
            model_name="following",
            name="following",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
