# Generated by Django 4.1.2 on 2022-11-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_relation_delete_following"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relation",
            old_name="Followers",
            new_name="followers",
        ),
        migrations.RenameField(
            model_name="relation",
            old_name="Following",
            new_name="following",
        ),
    ]
